### ISSUE TITLE
webui bug: incorrect display of "Up Speed" and "Down Speed" and "speed limit" problem

### ISSUE THREAD

**Issue by saburovga** [hadouken/hadouken#166] opened 2015-07-24 08:32 UTC
1. Upload speed display in "down speed" column
Download speed display in "up speed" column

2. Impossible enter value more than "999999" (it is equal 1000KB/s) in field "Maximum upload rate" and "Maximum download rate" in Preferences->Bandwidth.

English is not my native language and I can make some errors in this text. Sorry :)

**Comment by vktr** [comment] 2015-07-24 10:08
The upload/download speed issue is fixed in #161. I'll have a look at the input fields for 2.

**Comment by joshcano** [comment] 2015-07-24 16:29
Can you push the windows binary for 5.2? TY in advanced.

**Comment by vktr** [comment] 2015-07-24 17:56
@joshcano 5.2 haven't been released yet... However - for the DL/UL fix, see here, https://github.com/hadouken/hadouken/pull/161/files#diff-9b35e649895e7767f78f0dc6feeadb12. That file should be at `C:/ProgramData/Hadouken/js/rpc/webui_list.js` for a default installation.

**Comment by vktr** [comment] 2015-07-26 18:44
@saburovga The value you enter in "Maximum download rate" is in kb/s. To get 1000 kb/s you simply enter 1000 in that field. 999999 in that field would would be 999 mb/s.

**Comment by saburovga** [comment] 2015-07-27 05:55
Viktor, please see screenshots below
![2](https://cloud.githubusercontent.com/assets/9285992/8899442/22b589c8-343d-11e5-8077-c0d3e074d7d4.png)
![1](https://cloud.githubusercontent.com/assets/9285992/8899443/22b7f80c-343d-11e5-9da7-cdc6e9ae44dd.png)

**Comment by vktr** [comment] 2015-07-27 13:18
@saburovga I can't reproduce this... This is how I did,

- Enter `100000` in the *Maximum upload rate* and press Apply.
- Reload the UI (F5).
- The value `100000` is still in the rate limit field.
- Shut down Hadouken and the setting is in the config file as well.

**Comment by saburovga** [comment] 2015-07-27 13:35
Viktor, i try completely remove hadouken instance and reinstall them.

Please, tell me which folders and registry branch I must remove that completely remove information about hadouken installation? My OS is Windows 2008 SP2 (not R2) x64

P. S. Which OS you use for reproduce my bug?

**Comment by vktr** [comment] 2015-07-27 13:37
Uninstalling Hadouken via *Programs and features* will remove everything but the data. After uninstalling, remove the folder `C:/ProgramData/Hadouken` and you should have no traces left.

**Comment by vktr** [comment] 2015-08-04 07:58
Any updates on this? I'm trying to get as many issues fixed as possible for v5.2.

**Comment by saburovga** [comment] 2015-08-04 08:22
Hi, Viktor. Uninstall and clean install of Hadouken don't fix this problem for me :-(

I have hypothesis: may be this is locale-depend bug? My locale is "Russian".  In this locale uses comma as the decimal separator part, not a point. Unfortunately, I don't have english version of Windows distribution. I  tried change locale in my OS, but this don't fix bug.

**Comment by arion-p** [comment] 2015-08-28 22:41
I am having the same issue and my locale too uses comma as decimal separator. The values entered in up/down limits seem to be interpreted as bytes/sec instead of kbytes/sec.

(running v5.2)

**Comment by vktr** [comment] 2015-08-31 06:45
@arion-p Thanks, I'll have a look again.

**Comment by tinamil** [comment] 2015-09-15 17:56
Same issue here, but I'm running Windows 10 in a US-EN locale.  I'm trying to set a download rate limit of 5 MB/s, the webui is reading the value in bytes rather than kilobytes (e.g. inputting 999999 limits me to 1 MB/s), and the webui has a maximum input size of 6 digits and I need 7 digits to get to 5,000,000.  I was able to work around it by inputting a 999999 rate limit, restarting then stopping the service to write out the rate limit to the hadouken.json file, then editing the json file manually with the new limit and restarting the service again.  At that point Hadouken began using the 5MB/s rate limit I wanted.

**Closed** 2016-01-25 19:32 UTC
Labels: bug
