### ISSUE TITLE
Downloads stuck in DownloadingMetadata if recieved via CouchPatato

### ISSUE THREAD

**Issue by jwillmer** [hadouken/hadouken#129] opened 2015-06-14 17:44 UTC
If added manually it starts to download. Logfile looks similar for both actions.

**Comment by vktr** [comment] 2015-07-09 05:44
I can reproduce this.

The cause is missing trackers. The CouchPotato integration I wrote sends a list of trackers but Hadouken does not add them to the torrent.

This will be fixed in v5.

**Comment by vktr** [comment] 2015-07-09 15:27
Fixed in 4113ace29f98770f3c432b33c4f19341ad4f52ba.

**Closed by vktr** 2015-07-09 15:27 UTC
Labels: bug
