### ISSUE TITLE
Torrents getting stuck in listed as DownloadingMetadata while actually completing

### ISSUE THREAD

**Issue by Robo210** [hadouken/hadouken#86] opened 2014-11-07 05:41 UTC
![image](https://cloud.githubusercontent.com/assets/1312684/4948833/46d685b0-65fc-11e4-99fe-d919cffa30d1.png)

I've seen several torrents get stuck in a "DownloadingMetadata" state in the web interface, while actually successfully downloading and seeding. Refreshing the page doesn't fix it; I have to restart the service to get the torrent to show up properly.

I'm not entirely sure what causes this issue. I've been pasting URLs to .torrent files into the "Magnet link" URL field of the Add Torrent dialog (not actual magnet links), but this has worked fine before.

I'm using v4.6.0. As a bonus request, it would be nice to be able to find the version info in the web interface.

**Comment by vktr** [comment] 2015-04-05 09:05
Closing this since I cannot reproduce the error in v5. Please open a new issue if you're still seeing this bug.

**Closed by vktr** 2015-04-05 09:05 UTC
Labels: bug

**Comment by RyanGrange** [comment] 2015-04-29 21:10
Same problem for me in 4.7.0.  Can't remove entry from list.  Tried pasting a LibreOffice torrent as a magnet link and now I can't remove it.  File downloaded, but entry never progressed past the downloading metadata status.  All attempts at removing failed.

**Comment by RyanGrange** [comment] 2015-04-29 21:12
Fixed by restarting service after deleting file.  I'll avoid the magnet option in the future.
